- LICENSE
Copyright notices must reflect the current year. This commit updates the listed year to 2015 with a starting year of 2013.
https://github.com/gulpjs/gulp/commit/2357a4334051a6d1733037406ab7538255030d0b
> update MIT License to year range

- docs/recipes/split-tasks-across-multiple-files.md
Fenced code block used shell syntax highlighting, drawing attention to `test` unnecessarily:
Additionally, is there any advantage to declaring `var dir`? This works the same:
```js
var requireDir = require('require-dir');
requireDir('./tasks');
```
> Removed syntax highlighting from file structure

- docs/recipes/fast-browserify-builds-with-watchify.md
Uses gulp-util for time-stamped output of the same logs you'd get if you were running watchify directly.
> Adds build logging to gulp/watchify recipe

- docs/recipes/browserify-uglify-sourcemap.md
found it on:
https://medium.com/@sogko/gulp-browserify-the-gulp-y-way-bb359b3f9623
> suggesting a cleaner way

- docs/recipes/browserify-uglify-sourcemap.md
They didn't work before I made this change.
https://github.com/substack/node-browserify#var-b--browserifyfiles-or-opts
> Made browserify source maps actually work

- README.md
- docs/API.md
- docs/getting-started.md
- docs/recipes/browserify-uglify-sourcemap.md
- docs/recipes/combining-streams-to-handle-errors.md
- docs/recipes/delete-files-folder.md
- docs/recipes/incremental-builds-with-concatenate.md
- docs/recipes/maintain-directory-structure-while-globbing.md
- docs/recipes/make-stream-from-buffer.md
- docs/recipes/mocha-test-runner-with-gulp.md
- docs/recipes/running-tasks-in-series.md
- docs/recipes/server-with-livereload-and-css-injection.md
- docs/recipes/specifying-a-cwd.md
- docs/recipes/using-external-config-file.md
Also add the gulp.series and gulp.parallel APIs.
#803, #841 and #925
> Document the new gulp.task API.

- README.md
- docs/API.md
- add `gulp.lastRun` api doc.
- usage example in `README.md`
#841
> Update Documentation about incremental built

- docs/recipes/fast-browserify-builds-with-watchify.md
I don't know what the cause of this is. But I was absolutely not able to get the watchify recipe to work without changing the use of watchify to how it is in this PR.
This is also matches the examples given in the [watchify documentation](https://github.com/substack/watchify#var-w--watchifyb-opts).
> Use different use of watchify in recipe

- docs/API.md
- index.js
- Update API doc.
- recipes are unchanged; they didn’t use task name or task array for watch
#977
> remove array and string usage from gulp.watch

- docs/recipes/browserify-transforms.md
- docs/recipes/browserify-uglify-sourcemap.md
b.bundle has always been documented as returning a readable stream. The fact that some versions return a duplex stream is an implementation detail, and writing to it results in undefined behavior.
> docs(recipes): Browserify's undefined behavior is undefined.

- docs/recipes/browserify-transforms.md
- docs/recipes/browserify-with-globs.md
This pull request added missing `var sourcemaps = require('gulp-sourcemaps');` in browserify recipe.
> add missing gulp-sourcemaps in browserify recipe

- index.js
- test/watch.js
This is the PR addressing #1002. I found out that we not only have to deal with strings, but also with arrays (they have been used in a lot of documentation, too). This check makes those four little lines I added extremely ugly and hard to read. Input on that one is appreciated (esp. from you, @phated).
Also, tests have been added.
> checking for watch parameters, fixes #1002

- docs/recipes/fast-browserify-builds-with-watchify.md
I added browserify transforms in every call of `bundle()` and got increasing build times while running. 
Transformations have to be added once in the beginning as discussed in this question here: https://github.com/substack/watchify/issues/187#issuecomment-89687576
> Add a hint for browserify transforms

- docs/recipes/server-with-livereload-and-css-injection.md
As someone new to Gulp and still finding my feet, I naively copy and pasted the code from the CSS pre-processors section thinking it would just work (following the same conventions for directory layout as described in the simple example).
It does not just work however
* the `scss` directory is relative to the base directory (which is not the convention set out in the previous example)
* the `sass` tasks paths also similarly do not follow convention
* running just `grunt serve` as per the simple example does not invoke the `sass` task by default. (Of course you can run `grunt sass serve` but it seems more convenient if I could just run the same `grunt serve` as in the simple example - not sure if this is bad practice or not?)
Given the above, I've corrected the paths and add the `sass` …
> [recipes] Correct CSS pre-processors section

- .jshintrc
- package.json
- test/.jshintrc
- test/watch.js
JSHint was not run on the tests.
The failure is the same as in #1034, too long lines. Fix it, or ignore it in tests?
> Run JSHint on tests

- docs/API.md
This is a suggestion PR. Every time I pull up the api docs, I wish these links were there. They're intentionally formatted to one line for minimal disruption.
Looks like this:
> add quick links to api docs

- docs/recipes/running-task-steps-per-folder.md
Without the '/**' added the recipe is only useful for one level of subdirectories. With it, is usable for any number of them.
Also by adding the root variable as proposed also the root directory is processed.
> Make the recipe work for multiple levels of js directories and root

- docs/recipes/bump-version-and-create-git-tag.md
When executing the old bump-version-and-create-git-tag recipe the `commit-changes` task threw the error  `fatal: Paths with -a does not make sense`
With removing the -a option everything works as expected (since it seems that the -a flag is default anyway)
> Update gulp recipe bump-version-and-create-git-tag

- README.md
- docs/recipes/delete-files-folder.md
- docs/recipes/running-tasks-in-series.md
Pending [sindresorhus/del#29](https://github.com/sindresorhus/del/pull/29) and [sindresorhus/vinyl-paths#3](https://github.com/sindresorhus/vinyl-paths/pull/3). Do not merge yet.
This updates the gulp readme to reflect an upcoming version of `del` that returns a promise rather than receives a callback. It ends up cleaning its usage through gulp quite nicely since tasks can return promises to complete them \o/
> Update readme and recipes to reflect new Promise-oriented `del`

- docs/recipes/automate-release-workflow.md
the git.commit command as currently stated doesn't work on all environments. With windows and git version 1.9.5.msysgit.1 it works but with centos and git version 1.8.3.1 it doesn't. By adding the git.add() step it works in both environments
> Adds a git.add step in order to work on windows and linux

- index.js
Chokidar by default emits `add` events as it initially scans the file tree it is asked to watch. This can be suppressed by setting the `ignoreInitial: true` option, which is desirable here to avoid kicking off the task for each matched file upon startup.
Users retain the ability to specify `ignoreInitial: false` if that is the behavior they want.
Resolves #1282
> Set chokidar option ignoreIntial: true by default

- docs/API.md
It is possible to run tasks which only have dependencies, like so:
```js
gulp.task('build', ['array', 'of', 'task', 'names']);
```
So I added some documentation about it.
> Added documentation about tasks which only have dependencies

- docs/recipes/browserify-with-globs.md
The browserify globs example was no longer working with the latest version globby and I spent some time figuring out why. Turns out globby now uses Promise and has changed their API quite a bit.
> Update browserify globs example to work with the latest version of globby

- README.md
The current 'clean' task on provided example will return ```The following tasks did not complete``` warning. To fix it, either we need to return "del's" promise (>=2.0.0) or call a callback.
> Fix 'clean' task example code (4.0)

- docs/API.md
This aligns the example of custom task registry with Undertaker's docs. As promised in [#1319](https://github.com/gulpjs/gulp/issues/1319).
> Align API.md with undertaker docs

- docs/recipes/make-stream-from-buffer.md
Currently, we accumulate the start of the streams. As a result, the task ends before later processing is finished.
In my case, the later processing takes 20 seconds so it's very apparent.
> Recipe: Accumulate end of the streams, not start

- docs/API.md
I noticed that gulp.task docs don't have the task arguments' `Type: ` sections, so I added that.
I also put in a better example for a `gulp.task(name, function ( ) { } )` use case. The previous single line example was a little too simplified tbh.
> Fixed docs on gulp.task's optional arguments & provided a better example

- package.json
This will allow gulp to work with the new `babel-require` library for `*.babel.js` files
> Bump interpret to 1.0.0

- docs/API.md
- index.js
- test/watch.js
Except for the method signature in the end user docs, every indication is that `watch()` is supposed to work without a callback. But as a result of #1283, if you pass neither opts nor a callback it throws. This fixes that and updates the documentation of the method signature, and the prose about how callback is invoked.
> Make watch() work without opts or callback

- docs/getting-started.md
Closes #1451 
@contra How does this look?
> suggest gulp-cli in the getting started

- docs/recipes/running-task-steps-per-folder.md
Just felt that this may allow first time/early gulp users to comprehend what each line is doing a little more than having the comments as a block above. Having the line by line may help connect the dots.
> make comments easier to comprehend

- docs/getting-started.md
I've noticed this part is outdated, so I took this change from `master`.
> Use gulp-cli in Getting Started

- README.md
I added a new gulpfile sample from gulp 4.0 branch, more simple for new developers, who may not know about sourcemaps or coffee script, in my opinion and a version of it using **ES2015** with side notes about Babel installation requirement. [ issue  #1550 ]
_split view recommended_
> Added new gulpfile sample to README file with ES2015 version

- docs/recipes/README.md
- docs/recipes/browserify-multiple-destination.md
[Browserify+Globs](https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-with-globs.md) recipe bundles everything into one bundle, but doesn't show how to bundle each file into a separate bundle.
I think this example is helpful for people who want to create separate bundles from different entry files.
[This blog post](https://wehavefaces.net/gulp-browserify-the-gulp-y-way-bb359b3f9623) covers almost the same thing, but because of the change of browserify API now the examples in the above post doesn't work. (see https://github.com/substack/node-browserify/issues/1217 )
I believe it's helpful for beginners to have this example in the official recipes.
Thanks,
> Add browserify (multiple destination) example

- docs/API.md
This event type is fired when renaming a file.
> Add undocumented event.type

- docs/recipes/run-grunt-tasks-from-gulp.md
resubmit of #649 now that grunt 1.0.0 is released on npm as suggested in #646. @phated
> add `run-grunt-tasks-from-gulp` recipe

- docs/API.md
It is not apparent from the docs that src can be listened for when it finishes, which is immensely useful if performing a pipe after an asynchronous result. I've added an example to the documentation to surface this functionality, since I lost several hours puzzling over how to accomplish this task.
> Surface 'on' listener functionality

- README.md
`paths.images` in example isn't seen anywhere.
I've added a simple relevant example to avoid any confusion.
> 4.0 Readme: Update incremental builds example

- docs/recipes/minimal-browsersync-setup-with-gulp4.md
Hi,
I tried to setup BrowserSync with Gulp 4 & ES2015 today. The process was very pleasant so I thought I would share a quick recipe to get up and running with it. Let me know what you think.
> Add a minimal setup for BrowserSync with Gulp 4 & ES2015

- docs/API.md
`gulp.task(name [, deps, fn])` means that only `gulp.task(name, deps, fn)` and `gulp.task(name)` are allowed, which is apparently not the case and it's a bit confusing. The correct notation, `gulp.task(name [, deps] [, fn])`, also permits for `gulp.task(name, deps)`, and `gulp.task(name, fn)`.
> correct gulp.task signature

- docs/recipes/README.md
- docs/recipes/rollup-with-rollup-stream.md
The code is essentially the same as the first two examples from rollup-stream's README.md. Once [rollup-plugin-gulp](https://github.com/Permutatrix/rollup-plugin-gulp) earns the right to exist by having unit tests, I'll add a recipe for its use together with rollup-stream. That's assuming rollup-plugin-gulp turns out to be a good idea and not a horrifying aberration, of course.
> Add "Rollup with rollup-stream" recipe.

- docs/README.md
tagtree.io instead of tagtree.tv
> fix link to tagtree video

- package.json
Hey there, I noticed that gulp's info on npmjs has no keywords. 
Thought I'd do an easy fix for you by just switching out tags for keywords.
Hope you have a great day!
> Replace tags with keywords in package.json

- docs/CLI.md
This clarifies the semantics brought up in #1915 and makes a tiny bit of progress on #1595
> Docs: Clarify CLI semantics when listing more than one task

- README.md
Tweak and add to the ES6 task exporting examples in the README.
See the [rich diff](https://github.com/gulpjs/gulp/commit/d780de55e25955b87e4d88f8969771fb6b44975c?w=1&short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) for details.
> Improve ES2015 task exporting examples for 4.0

- docs/recipes/README.md
- docs/recipes/cron-task.md
The main point of this is to provide documentation
when you get the following error in the cron logs
after trying to run a gulp task:
> /usr/bin/env: node: No such file or directory
Resolves #2033.
> docs(recipe): Running gulp via cron task

- docs/recipes/browserify-transforms.md
- docs/recipes/browserify-uglify-sourcemap.md
- docs/recipes/fast-browserify-builds-with-watchify.md
Changed old link:
http://github.com/substack/node-browserify -> https://github.com/browserify/browserify
Changed old link:
http://github.com/substack/watchify -> https://github.com/browserify/watchify
> Update Github links for browserify in docs

- docs/API.md
Because the master branch is the authoritative source of documentation, it can be confusing for developers who have used `npm install gulp` (or joined a project using gulp 3) that the master branch is for a different major release. This PR adds a simple notification to the API docs, which are linked to from https://gulpjs.com/, that the standard version installed by `npm install gulp`.
It's worth noting that, while it might be obvious to people familiar with gulp's development, there's no indication that there's a mismatch between master and the current node release anywhere on `https://gulpjs.com/`, nor on `master:docs/API.md`, nor in any of the top google search results for "gulpjs documentation".
> Added notice for 4.0.0 vs 3.9.1 documentation

- docs/recipes/running-task-steps-per-folder.md
Just corrected the variable name to ```folders``` in the folder recipe.
> fix: typo in code in recipe for running tasks in folders

- docs/api/src.md
> Content Edits

- docs/api/symlink.md
Fixed a markdown formatting error and removed an extra word.
> Small content edits

- README.md
How's this look?  Am I blatantly missing anything?
@contra @stevelacy @terinjokes @erikkemperman
> Docs: Add "What's new in 4.0" section (closes #2089)

- README.md
We want to start guiding people towards 4.0 patterns and using our website.  Also did some housekeeping.
cc @contra @terinjokes @demurgos @stevelacy @janiceilene
> Docs: Cleanup README for "latest" bump

- docs/getting-started/2-javascript-and-gulpfiles.md
> To be more explicit regarding transpilation

- docs/getting-started/7-using-plugins.md
Hey gulpjs,
First off thank you for the awesome build tool!
I'm in the process of rewriting my front end gulpfile and found that the example for uglifying js passed an object into a Buffer that accepts a string. This commit fixes that reference.
Sincerely,
Bryan Stoner
> fix broken doc code

- docs/api/vinyl.md
After changing the stem to foo and the ext to .js, the full path should be `/specs/foo.js`
> Typo in last line of usage example

- docs/getting-started/7-using-plugins.md
Rollup is imported by name, so it should be called like `rollup()`.
> Correct typo in rollup example

- docs/getting-started/4-async-completion.md
The code example on the [Async Completion](https://gulpjs.com/docs/en/getting-started/async-completion) page was meant to log the version from package.json to the console, but it was logging out "undefined".
Output of previous code example:
Output of fixed code example:
> Fix for code example in documentation (Getting Started/Async Completion)

- docs/recipes/rollup-with-rollup-stream.md
Just a couple of deprecated properties. Additionally, specifying format is mandatory now or rollup complains.
> Update rollup recipe

- CONTRIBUTING.md
Hi 😸 
`https://github.com/gulpjs/gulp/blob/4.0/index.js` is 404.
This PR is a tiny fix.
> Docs: fix link URL on CONTRIBUTING.md

- docs/advanced/creating-custom-registries.md
- docs/api/registry.md
- docs/getting-started/9-creating-custom-registries.md
This PR picks up the "Creating custom registries" bullet point from #2256 
While writing this, I found that in the [undertaker](https://github.com/gulpjs/undertaker#registryregistryinstance) README, `registry()` is partially explained already, but I felt that just copy-pasting wasn't enough and the document here is a bit more thorough on what's exactly required or happening.
I also decided to link to all of the PoC registries that have been created in the organization beforehand, so people have some more starting points.
> Docs: Detail creation of custom registries

- docs/recipes/automate-release-workflow.md
🔥 🔥 🔥 
- infer version bump from commits
- make release commit message adhere to Conventional Commits
- read GitHub personal access token from git-ignored `.env` file
- functions instead of `gulp.task`
- eliminate usage of gulp plugins
- improve readability with `execa` and `pify`
I like this recipe because it can be used as inspiration even by those who want to build something completely different.
Ref. #2164.
> Docs: Update and refactor release workflow recipe

- docs/recipes/minimal-browsersync-setup-with-gulp4.md
Hi there, just updated broken readme link. Thanks!
> Updated broken Readme link

- docs/recipes/browserify-transforms.md
The gulp-sourcemaps plugin can be removed.
Gulp already has built-in support for source maps.
https://gulpjs.com/docs/en/api/src/#sourcemaps
> Removed the gulp-sourcemaps plugin

- docs/writing-a-plugin/README.md
Link referenced to stream-handbook is wrong 
This is my first public PR hope this link is correct.
Updated Link - https://www.npmjs.com/package/stream-handbook
> Updated Invalid Link [Docs | Stream-Handbook]

- README.md
- index.mjs
- package.json
- test/fixtures/gulpfiles/mjs/gulpfile.mjs
- test/index.test.js
This implements an ESM wrapper following the Node.js docs for [Writing dual packages while avoiding or minimizing hazards](https://nodejs.org/docs/latest/api/packages.html#writing-dual-packages-while-avoiding-or-minimizing-hazards)
The test seems to work but I'm unsure if there is anything I need to do for the `bin` file. Perhaps someone else knows.
Closes #2634
> feat: Provide an ESM export

- CHANGELOG.md
Release Please is great, but gulp is a small layer on top of 60+ dependencies. We don't get any of their changes surfaced in our Changelog, so I've done it by hand.
> chore: Update changelog for all subprojects

- docs/getting-started/6-explaining-globs.md
This updates the docs to mentioned the gulp 5 alternative to ordered globs.
Ref #2764
Ref #2784
> chore: Update glob docs with replacement to ordered globs

- package.json
Upgrading gulp-cli to support top-level await in Node 22.12+
Since this version and newer started support `require(esm)`, a different error was thrown if a top-level await was encountered. We needed to add support in gulp-cli to support it.
> fix: Support top-level await on Node 22.12+

- package.json
The upgrades vinyl-fs to ensure that the newest glob-stream is pulled in which fixes an issue where globbing could complete before the stream was opened resulting to missed files/incomplete streams/etc.
I think this resolves some issues users were encountering but we'll ask them to test the new version once released before closing them out.
Ref #2807
Ref #2811
> fix: Avoid globbing before read stream is opened
