gulpjs/gulp

README.md
* rearranged the badges so that everything still fits in one line.
=> add gitter badge and rearrange badge line

docs/recipes/server-with-livereload-and-css-injection.md
See https://github.com/sindresorhus/gulp-ruby-sass/issues/185
=> Update gulp-ruby-sass syntax (1.0.0)

CONTRIBUTING.md
=> Update gulp core team GitHub link

docs/recipes/mocha-test-runner-with-gulp.md
I'm being pretty pedantic here but it might catch out new users. It caught me out for a few secs.. :)
=> Adding gulp-util to the npm install line

package.json
=> bump interpret

docs/getting-started.md
Reverts gulpjs/gulp#928
We can't promote this yet.
=> Revert "install cli globally"

.jscsrc, bin/gulp.js, lib/completion.js, lib/taskTree.js, package.json, test/dest.js, test/src.js, test/taskTree.js, test/tasks.js, test/watch.js
=> Bring JSCS to Gulp

README.md
=> Rewrite gulpfile example

CHANGELOG.md, docs/API.md
=> Update doc and change log regarding task name

docs/API.md, docs/CLI.md
=> Add .description doc

docs/recipes/browserify-uglify-sourcemap.md
Added error output for Uglify, so that it doesn't just fail silently.
=> Uglify now outputs error in Browserify/Uglify/Sourcemap recipe

docs/recipes/README.md, docs/recipes/browserify-transforms.md, docs/recipes/browserify-with-globs.md
Adopted the example given in the Browserify issue tracker, as discussed with @phated.
@phated fill free to nit-pick any of the comments. I what to make sure you're happy with how it's worded and how you think others would interpret.
=> docs(recipes): Adds Browserify + Globs

docs/API.md, docs/CLI.md
As discussed in #1004 
No code changes
=> docs(gulp.tree): document gulp.tree API

docs/CLI.md, docs/writing-a-plugin/testing.md
I am translating gulp docs to Simplified Chinese, and I just find these.
It's all work fine, but it can be more accurate. :P
=> Improve the docs

docs/recipes/make-stream-from-buffer.md
=> change lib files to version files

docs/README.md
Added Simplified Chinese documentation link #1148
=> add Simplified Chinese documentation link

docs/writing-a-plugin/guidelines.md
=> Added plugin naming guidelines

docs/writing-a-plugin/guidelines.md
=> fix grammar in writing a plugin

README.md
Removed unneeded possessive apostrophe.
=> Grammatical fix

docs/recipes/running-tasks-in-series.md
Clarify one of the examples to make it clearer where the variable `err` is coming from.
Issue at https://github.com/gulpjs/gulp/issues/1092#issuecomment-124716362.
=> Docs: Clarify err usage

docs/recipes/README.md
With tiny stuff like this am I fine to push straight to master or do you want PRs for everything still?
=> Updated link to renamed recipe

.travis.yml
=> Change node 4.0.0 to stable version.

docs/API.md, docs/recipes/handling-the-delete-event-on-watch.md, index.js, package.json, test/watch.js
I gave integrating chokidar a shot. I hope you don't mind @es128. I see it as some exercise for me, so if you have any better solution, I don't mind having this PR going down ;-)
Naturally, I felt really uncomfortable changing tests ;-) But due to chokidar's different API, I had to. The changes were rather small, though. I also updated the recipes and docs.
Looking forward to your feedback
Fixes #1247
=> Moving from vinyl-fs watch (gaze) to chokidar, fixes #1247

docs/API.md
=> Add detail to watch docs

docs/README.md
* Add  KR translations link to main docs
Not fully completed. but almost guide docs are completely translated. (except writing-a-plugin)
I will translate remains later.
=> Add KR translations link

test/watch.js
Not sure if this is worth much. But I added this test to double check some foobars I had locally. This was to verify functionality.
=> added a spec to make sure no functions are kicked off when they should not be

docs/API.md
=> documents glob negation

docs/writing-a-plugin/README.md
This is my initial draft of additional documentation as discussed in #962.  At the moment, a lot of this is me thinking "out loud", but it may be helpful to others.
=> Document plugin AP

docs/API.md
=> Improve format of v4 API doc.

docs/README.md
Very straight forward tutorial for automating common tasks. 
https://scotch.io/tutorials/automate-your-tasks-easily-with-gulp-js
=> Adding scotch.io article

README.md
According to http://gulpjs.com/plugins, there are already much more. This replaces #1391.
=> Increase number of plugins and highlight it

docs/FAQ.md
Updated to replace IRC with Gitter room.
=> Updating FAQ to share Gitter channel instead of IRC

docs/recipes/README.md, docs/recipes/exports-as-tasks.md
=> Add exports as tasks docs

docs/README.md
Presented by @addyosmani and @gauntface.
=> Doc: Add video "Intro to Gulp 4"

docs/API.md, docs/recipes/README.md, docs/recipes/specifying-a-cwd.md
- fix links I did not notice in the last PR.
- adds simple webpack example since there are 4 browserify examples.
=> Fix remaining links + add webpack example

docs/recipes/split-tasks-across-multiple-files.md
@phated, I've added a deprecation notice as we discussed with another commit.
=> Updated «Split tasks across multiple files» recipe

docs/recipes/run-grunt-tasks-from-gulp.md
Hi, I am Feram 🤖
I'm a bot and I work in behalf of [adius](https://github.com/adius).
As I'm just a dumb program this pull request might be incomplete
or utterly nonsense.
I hope, however, that I was able to improve this repository!
If I didn't behave please [report me](https://github.com/adius/feram/issues) to my Dad
and he will give me a proper punishment.
Love, hugs and kisses,
your [Feram](https://github.com/adius/feram)
=> Minor fixes

docs/recipes/browserify-with-globs.md
=> Fix small typo

docs/recipes/mocha-test-runner-with-gulp.md
Previously, the app would throw the error:
"Task 'default' is not in your gulpfile"
=> Bottom example is now runnable

docs/recipes/exports-as-tasks.md
Reference to comment in #1445 - adding note to let folks know this only works with the latest published gulp-cli version
=> Add note for compatibility with gulp 3.x 

docs/recipes/minimal-browsersync-setup-with-gulp4.md
@phated I'm terribly sorry there was a small mistake in the version I submitted yesterday. Hope you don't mind merging another commit.
=> Fix Gulp4 docs browsersync example

CHANGELOG.md
=> Fix changelog typos

bin/gulp.js
=> Linting - few extra commas

.github/ISSUE_TEMPLATE.md
This is a bit more obvious than the "Please review the guidelines for contributing to this repository." banner - the user has to active delete the text to make an issue.
Also put in an actual template, which should help a bit for actual bug reports :)
@contra @phated: Thoughts?
=> Create issue template to cover common issues

docs/recipes/server-with-livereload-and-css-injection.md
=> Fix syntax

docs/writing-a-plugin/guidelines.md
=> (docs): Fix broken header and footer links 

docs/writing-a-plugin/guidelines.md
At the moment, rule numbers are showing as 1, 1, 1... etc
=> Fix rule numbers

README.md, docs/API.md, docs/CLI.md, docs/FAQ.md, docs/README.md, docs/getting-started.md, docs/recipes/browserify-transforms.md, docs/recipes/browserify-uglify-sourcemap.md, docs/recipes/fast-browserify-builds-with-watchify.md, docs/recipes/rollup-with-rollup-stream.md, docs/recipes/server-with-livereload-and-css-injection.md, docs/writing-a-plugin/README.md
URLs were updated to use HTTPS protocol
=> Update HTTP -> HTTPS

docs/api/tree.md
=> Small content changes

.ci/.azure-pipelines-steps.yml
=> Build: Fix Azure comment

README.md
Follow up to #2299. Would probably be good to have if we're deciding to keep Pipelines around.
=> Consider adding Azure Pipelines badge

README.md
When I wrote this a handful of years back we only had ~2K, now we have almost 3.5K in the ecosystem
=> Docs: Update README plugin count

README.md
=> Added missing punctuation

docs/README.md, docs/locale/pl_PL/README.md, docs/locale/pl_PL/api/concepts.md, docs/locale/pl_PL/getting-started/1-quick-start.md, docs/locale/pl_PL/getting-started/2-javascript-and-gulpfiles.md
Hi. First of all, really great idea & project!
Here is Polish version 🔥
https://github.com/mbiesiad/gulp/tree/pl_PL/docs
Changes [here](https://github.com/gulpjs/gulp/pull/2456/files)
Best wishes,
=> Add Polish Documentation 

docs/recipes/README.md
Follow up https://github.com/gulpjs/gulp/commit/d51c6eb8ff51bc7d251f30e1b15288b72492c384
=> Docs: fix link in recipes
